version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - django_rest_api/.env
    volumes:
      - .:/django_rest_api
    depends_on:
      - db
    restart: always

  celery:
    build: .
    command: celery -A news_board worker -l info
    volumes:
      - .:/
    links:
      - redisnews_board
    depends_on:
      - web
      - db
      - redis
    restart: always

  celery-beat:
    build: .
    command: celery -A news_board beat -l info
    volumes:
      - .:/news_board
    links:
      - redis
    depends_on:
      - web
      - db
      - redis
    restart: always

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - 6379:6379
    restart: always

  db:
    image: postgres:13-alpine
    env_file:
      - django_rest_api/.env
    restart: always